name: Deploy .NET Framework App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # 3. Setup NuGet
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    # 4. Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore CurrencyConverter.sln

    # 5. Build application
    - name: Build project
      run: msbuild CurrencyConverter.sln /p:Configuration=Release

    # 6. Deploy (FTP example)
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ftps://your-server.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./CurrencyConverter/bin/Release/
        remote-dir: /public_html/
